//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrNajeeb.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.AspNetUsers1 = new HashSet<AspNetUser>();
            this.AspNetUsers11 = new HashSet<AspNetUser>();
            this.AspNetUsers12 = new HashSet<AspNetUser>();
            this.AspNetUsers13 = new HashSet<AspNetUser>();
            this.Categories = new HashSet<Category>();
            this.Categories1 = new HashSet<Category>();
            this.Categories2 = new HashSet<Category>();
            this.Categories3 = new HashSet<Category>();
            this.CategoryVideos = new HashSet<CategoryVideo>();
            this.CategoryVideos1 = new HashSet<CategoryVideo>();
            this.IpAddressFilters = new HashSet<IpAddressFilter>();
            this.IpAddressFilters1 = new HashSet<IpAddressFilter>();
            this.IpAddressFilters2 = new HashSet<IpAddressFilter>();
            this.IpAddressFilters3 = new HashSet<IpAddressFilter>();
            this.Subscriptions = new HashSet<Subscription>();
            this.Subscriptions1 = new HashSet<Subscription>();
            this.Subscriptions2 = new HashSet<Subscription>();
            this.Subscriptions3 = new HashSet<Subscription>();
            this.SupportMessages = new HashSet<SupportMessage>();
            this.SupportMessages1 = new HashSet<SupportMessage>();
            this.UserFavoriteVideos = new HashSet<UserFavoriteVideo>();
            this.UserVideoHistories = new HashSet<UserVideoHistory>();
            this.Videos = new HashSet<Video>();
            this.Videos1 = new HashSet<Video>();
            this.Videos2 = new HashSet<Video>();
            this.Videos3 = new HashSet<Video>();
            this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public bool IsPasswordReset { get; set; }
        public bool IsAllowMobileVideos { get; set; }
        public bool IsParentalControl { get; set; }
        public string ParentalControlPin { get; set; }
        public bool IsFilterByIP { get; set; }
        public int NoOfConcurentViews { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> SubscriptionId { get; set; }
        public bool IsActiveUSer { get; set; }
        public int CurrentViews { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> SubscriptionDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string ProfilePicture { get; set; }
        public Nullable<bool> IsFreeUser { get; set; }
    
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers1 { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers11 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual Subscription Subscription { get; set; }
        public virtual Subscription Subscription1 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers12 { get; set; }
        public virtual AspNetUser AspNetUser3 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers13 { get; set; }
        public virtual AspNetUser AspNetUser4 { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Category> Categories1 { get; set; }
        public virtual ICollection<Category> Categories2 { get; set; }
        public virtual ICollection<Category> Categories3 { get; set; }
        public virtual ICollection<CategoryVideo> CategoryVideos { get; set; }
        public virtual ICollection<CategoryVideo> CategoryVideos1 { get; set; }
        public virtual ICollection<IpAddressFilter> IpAddressFilters { get; set; }
        public virtual ICollection<IpAddressFilter> IpAddressFilters1 { get; set; }
        public virtual ICollection<IpAddressFilter> IpAddressFilters2 { get; set; }
        public virtual ICollection<IpAddressFilter> IpAddressFilters3 { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
        public virtual ICollection<Subscription> Subscriptions1 { get; set; }
        public virtual ICollection<Subscription> Subscriptions2 { get; set; }
        public virtual ICollection<Subscription> Subscriptions3 { get; set; }
        public virtual ICollection<SupportMessage> SupportMessages { get; set; }
        public virtual ICollection<SupportMessage> SupportMessages1 { get; set; }
        public virtual ICollection<UserFavoriteVideo> UserFavoriteVideos { get; set; }
        public virtual ICollection<UserVideoHistory> UserVideoHistories { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
        public virtual ICollection<Video> Videos1 { get; set; }
        public virtual ICollection<Video> Videos2 { get; set; }
        public virtual ICollection<Video> Videos3 { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}
