//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrNajeeb.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public Subscription()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.AspNetUsers1 = new HashSet<AspNetUser>();
            this.AspNetUsers2 = new HashSet<AspNetUser>();
            this.AspNetUsers3 = new HashSet<AspNetUser>();
            this.AspNetUsers4 = new HashSet<AspNetUser>();
            this.AspNetUsers5 = new HashSet<AspNetUser>();
            this.AspNetUsers6 = new HashSet<AspNetUser>();
            this.AspNetUsers7 = new HashSet<AspNetUser>();
            this.CategoriesInSubscriptions = new HashSet<CategoriesInSubscription>();
            this.CategoriesInSubscriptions1 = new HashSet<CategoriesInSubscription>();
            this.CategoriesInSubscriptions2 = new HashSet<CategoriesInSubscription>();
            this.CategoriesInSubscriptions3 = new HashSet<CategoriesInSubscription>();
            this.CategoriesInSubscriptions4 = new HashSet<CategoriesInSubscription>();
            this.CategoriesInSubscriptions5 = new HashSet<CategoriesInSubscription>();
            this.CategoriesInSubscriptions6 = new HashSet<CategoriesInSubscription>();
            this.CategoriesInSubscriptions7 = new HashSet<CategoriesInSubscription>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> TimeDuration { get; set; }
        public string GatewayId { get; set; }
        public string GatewayURL { get; set; }
        public bool IsActiveSubscription { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers1 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers2 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers3 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers4 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers5 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers6 { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers7 { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual AspNetUser AspNetUser3 { get; set; }
        public virtual AspNetUser AspNetUser4 { get; set; }
        public virtual AspNetUser AspNetUser5 { get; set; }
        public virtual AspNetUser AspNetUser6 { get; set; }
        public virtual AspNetUser AspNetUser7 { get; set; }
        public virtual AspNetUser AspNetUser8 { get; set; }
        public virtual AspNetUser AspNetUser9 { get; set; }
        public virtual AspNetUser AspNetUser10 { get; set; }
        public virtual AspNetUser AspNetUser11 { get; set; }
        public virtual AspNetUser AspNetUser12 { get; set; }
        public virtual AspNetUser AspNetUser13 { get; set; }
        public virtual AspNetUser AspNetUser14 { get; set; }
        public virtual AspNetUser AspNetUser15 { get; set; }
        public virtual ICollection<CategoriesInSubscription> CategoriesInSubscriptions { get; set; }
        public virtual ICollection<CategoriesInSubscription> CategoriesInSubscriptions1 { get; set; }
        public virtual ICollection<CategoriesInSubscription> CategoriesInSubscriptions2 { get; set; }
        public virtual ICollection<CategoriesInSubscription> CategoriesInSubscriptions3 { get; set; }
        public virtual ICollection<CategoriesInSubscription> CategoriesInSubscriptions4 { get; set; }
        public virtual ICollection<CategoriesInSubscription> CategoriesInSubscriptions5 { get; set; }
        public virtual ICollection<CategoriesInSubscription> CategoriesInSubscriptions6 { get; set; }
        public virtual ICollection<CategoriesInSubscription> CategoriesInSubscriptions7 { get; set; }
    }
}
