//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrNajeeb.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportMessage
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> MessageDatetime { get; set; }
        public string MessageText { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public string FromUserId { get; set; }
        public string ToUserId { get; set; }
        public Nullable<bool> IsFromAdmin { get; set; }
        public Nullable<bool> IsFromUser { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual AspNetUser AspNetUser3 { get; set; }
        public virtual AspNetUser AspNetUser4 { get; set; }
        public virtual AspNetUser AspNetUser5 { get; set; }
        public virtual AspNetUser AspNetUser6 { get; set; }
        public virtual AspNetUser AspNetUser7 { get; set; }
    }
}
