//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrNajeeb.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public Video()
        {
            this.CategoryVideos = new HashSet<CategoryVideo>();
            this.CategoryVideos1 = new HashSet<CategoryVideo>();
            this.CategoryVideos2 = new HashSet<CategoryVideo>();
            this.CategoryVideos3 = new HashSet<CategoryVideo>();
            this.CategoryVideos4 = new HashSet<CategoryVideo>();
            this.CategoryVideos5 = new HashSet<CategoryVideo>();
            this.CategoryVideos6 = new HashSet<CategoryVideo>();
            this.CategoryVideos7 = new HashSet<CategoryVideo>();
            this.UserFavoriteVideos = new HashSet<UserFavoriteVideo>();
            this.UserFavoriteVideos1 = new HashSet<UserFavoriteVideo>();
            this.UserFavoriteVideos2 = new HashSet<UserFavoriteVideo>();
            this.UserFavoriteVideos3 = new HashSet<UserFavoriteVideo>();
            this.UserVideoHistories = new HashSet<UserVideoHistory>();
            this.UserVideoHistories1 = new HashSet<UserVideoHistory>();
            this.UserVideoHistories2 = new HashSet<UserVideoHistory>();
            this.UserVideoHistories3 = new HashSet<UserVideoHistory>();
            this.VideoDownloadhistories = new HashSet<VideoDownloadhistory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Duration { get; set; }
        public int ReleaseYear { get; set; }
        public System.DateTime DateLive { get; set; }
        public string BackgroundColor { get; set; }
        public string ThumbnailURL { get; set; }
        public string PreviewURL { get; set; }
        public string SpecialFeatureURL { get; set; }
        public string BackgroundImageURL { get; set; }
        public string VideoPlayerImageURL { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsFeatured { get; set; }
        public bool IsMatureContent { get; set; }
        public bool IsShowInPromo { get; set; }
        public string StandardVideoId { get; set; }
        public string FastVideoId { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsFreeVideo { get; set; }
        public int FreeVideoOrder { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
        public virtual AspNetUser AspNetUser3 { get; set; }
        public virtual AspNetUser AspNetUser4 { get; set; }
        public virtual AspNetUser AspNetUser5 { get; set; }
        public virtual AspNetUser AspNetUser6 { get; set; }
        public virtual AspNetUser AspNetUser7 { get; set; }
        public virtual AspNetUser AspNetUser8 { get; set; }
        public virtual AspNetUser AspNetUser9 { get; set; }
        public virtual AspNetUser AspNetUser10 { get; set; }
        public virtual AspNetUser AspNetUser11 { get; set; }
        public virtual AspNetUser AspNetUser12 { get; set; }
        public virtual AspNetUser AspNetUser13 { get; set; }
        public virtual AspNetUser AspNetUser14 { get; set; }
        public virtual AspNetUser AspNetUser15 { get; set; }
        public virtual ICollection<CategoryVideo> CategoryVideos { get; set; }
        public virtual ICollection<CategoryVideo> CategoryVideos1 { get; set; }
        public virtual ICollection<CategoryVideo> CategoryVideos2 { get; set; }
        public virtual ICollection<CategoryVideo> CategoryVideos3 { get; set; }
        public virtual ICollection<CategoryVideo> CategoryVideos4 { get; set; }
        public virtual ICollection<CategoryVideo> CategoryVideos5 { get; set; }
        public virtual ICollection<CategoryVideo> CategoryVideos6 { get; set; }
        public virtual ICollection<CategoryVideo> CategoryVideos7 { get; set; }
        public virtual ICollection<UserFavoriteVideo> UserFavoriteVideos { get; set; }
        public virtual ICollection<UserFavoriteVideo> UserFavoriteVideos1 { get; set; }
        public virtual ICollection<UserFavoriteVideo> UserFavoriteVideos2 { get; set; }
        public virtual ICollection<UserFavoriteVideo> UserFavoriteVideos3 { get; set; }
        public virtual ICollection<UserVideoHistory> UserVideoHistories { get; set; }
        public virtual ICollection<UserVideoHistory> UserVideoHistories1 { get; set; }
        public virtual ICollection<UserVideoHistory> UserVideoHistories2 { get; set; }
        public virtual ICollection<UserVideoHistory> UserVideoHistories3 { get; set; }
        public virtual ICollection<VideoDownloadhistory> VideoDownloadhistories { get; set; }
    }
}
